[project]
name = "agentic-pharma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "faiss-cpu>=1.12.0",
    "fastapi>=0.120.4",
    "langgraph>=0.6.11",
]
